export interface CountryEntry {
  code: string;
  name: string;
  currency: string;
  currencyName: string;
  figures?: string; // Visual descriptions to help identify
}

export interface ScriptGroup {
  id: string;
  nameKey: string;
  icon: string;
  description?: string;
  countries: CountryEntry[];
}

export const SCRIPT_GROUPS: ScriptGroup[] = [
  // ─── By Script/Alphabet ─────────────────────────────────────────────────
  {
    id: "latin",
    nameKey: "identify.scripts.latin",
    icon: "text-outline",
    countries: [
      { code: "US", name: "United States", currency: "USD", currencyName: "Dollar", figures: "Green banknote, portrait of man in wig (1$), man with beard (5$), bald man with glasses (100$)" },
      { code: "DE", name: "European Union", currency: "EUR", currencyName: "Euro", figures: "Colorful, bridges & windows drawings (no portraits), map of Europe on back" },
      { code: "GB", name: "United Kingdom", currency: "GBP", currencyName: "Pound", figures: "Elderly woman with crown (Queen) or man with crown (King), purple/orange/green" },
      { code: "CA", name: "Canada", currency: "CAD", currencyName: "Dollar", figures: "Plastic/polymer, transparent maple leaf window, elderly woman or man portrait" },
      { code: "AU", name: "Australia", currency: "AUD", currencyName: "Dollar", figures: "Plastic/polymer, transparent oval window, colorful, portraits of men/women" },
      { code: "NZ", name: "New Zealand", currency: "NZD", currencyName: "Dollar", figures: "Plastic/polymer, transparent fern window, mountain climber (5$), colorful birds" },
      { code: "CH", name: "Switzerland", currency: "CHF", currencyName: "Franc", figures: "Vertical format, hand drawings, colorful abstract art, very modern design" },
      { code: "NO", name: "Norway", currency: "NOK", currencyName: "Krone", figures: "Lighthouse, fish, ship on one side; pixel art ocean/waves on other" },
      { code: "SE", name: "Sweden", currency: "SEK", currencyName: "Krona", figures: "Portraits of women, nature scenes, modern design" },
      { code: "DK", name: "Denmark", currency: "DKK", currencyName: "Krone", figures: "Bridges on front, map details, prehistoric artifacts" },
      { code: "IS", name: "Iceland", currency: "ISK", currencyName: "Króna", figures: "Portraits of elderly men, blue/green/brown tones" },
      { code: "CZ", name: "Czechia", currency: "CZK", currencyName: "Koruna", figures: "Man with mustache and glasses, castle, Gothic cathedral" },
      { code: "HU", name: "Hungary", currency: "HUF", currencyName: "Forint", figures: "Historical kings with crown, castles, bridges" },
      { code: "PL", name: "Poland", currency: "PLN", currencyName: "Złoty", figures: "Medieval kings and queens, eagles, castles" },
      { code: "RO", name: "Romania", currency: "RON", currencyName: "Leu", figures: "Plastic/polymer, portraits of bearded men, flowers, churches" },
      { code: "HR", name: "Croatia", currency: "EUR", currencyName: "Euro (ex-Kuna)", figures: "Previously colorful Kuna notes with cities, now uses Euro" },
      { code: "AL", name: "Albania", currency: "ALL", currencyName: "Lek", figures: "Man with fez hat, ancient ruins, eagles" },
      { code: "MX", name: "Mexico", currency: "MXN", currencyName: "Peso", figures: "Pink 50 peso, woman with flowers in hair (Frida), ancient Aztec art, eagle eating snake" },
      { code: "BR", name: "Brazil", currency: "BRL", currencyName: "Real", figures: "Woman statue head on all notes, animals on back: jaguar, turtle, parrot, monkey" },
      { code: "AR", name: "Argentina", currency: "ARS", currencyName: "Peso", figures: "Blonde woman (Eva Perón), man on horse, condor, blue/pink tones" },
      { code: "CL", name: "Chile", currency: "CLP", currencyName: "Peso", figures: "Man in naval uniform, woman portrait, poet, desert landscapes" },
      { code: "CO", name: "Colombia", currency: "COP", currencyName: "Peso", figures: "Man in military uniform, butterflies, frogs, colorful nature" },
      { code: "PE", name: "Peru", currency: "PEN", currencyName: "Sol", figures: "Woman with veil (saint), Machu Picchu, ancient ruins" },
      { code: "VE", name: "Venezuela", currency: "VES", currencyName: "Bolívar", figures: "Man with curly hair in military uniform on all notes" },
      { code: "UY", name: "Uruguay", currency: "UYU", currencyName: "Peso", figures: "Man with sideburns in military uniform" },
      { code: "PY", name: "Paraguay", currency: "PYG", currencyName: "Guaraní", figures: "Man in dark suit, dam, nature scenes" },
      { code: "BO", name: "Bolivia", currency: "BOB", currencyName: "Boliviano", figures: "Man in military uniform, mountains, llamas" },
      { code: "EC", name: "Ecuador", currency: "USD", currencyName: "Dollar (uses USD)" },
      { code: "CU", name: "Cuba", currency: "CUP", currencyName: "Peso", figures: "Man with beret and star (Che Guevara 3$), man with mustache, monument" },
      { code: "CR", name: "Costa Rica", currency: "CRC", currencyName: "Colón", figures: "Colorful butterflies, sloths, coral reefs, very colorful polymer" },
      { code: "GT", name: "Guatemala", currency: "GTQ", currencyName: "Quetzal", figures: "Colorful bird (Quetzal), man with feather headdress" },
      { code: "HN", name: "Honduras", currency: "HNL", currencyName: "Lempira", figures: "Indigenous chief with headdress" },
      { code: "NI", name: "Nicaragua", currency: "NIO", currencyName: "Córdoba", figures: "Castle/fortress, colorful, Spanish colonial buildings" },
      { code: "PA", name: "Panama", currency: "PAB", currencyName: "Balboa", figures: "Man with helmet (conquistador), Panama Canal" },
      { code: "DO", name: "Dominican Republic", currency: "DOP", currencyName: "Peso", figures: "Founding fathers, cathedral, colorful" },
      { code: "JM", name: "Jamaica", currency: "JMD", currencyName: "Dollar", figures: "Man with dreadlocks vibe, hummingbird, colorful" },
      { code: "TT", name: "Trinidad & Tobago", currency: "TTD", currencyName: "Dollar", figures: "Red bird (scarlet ibis), tropical flowers" },
      { code: "ID", name: "Indonesia", currency: "IDR", currencyName: "Rupiah", figures: "Man with traditional cap (peci), dancers, temples, red/green tones" },
      { code: "PH", name: "Philippines", currency: "PHP", currencyName: "Piso", figures: "Man with glasses, eagles, whale shark, colorful" },
      { code: "MY", name: "Malaysia", currency: "MYR", currencyName: "Ringgit", figures: "Man with traditional songkok hat on all notes, blue/green/red, hibiscus flower" },
      { code: "SG", name: "Singapore", currency: "SGD", currencyName: "Dollar", figures: "Man with glasses on all notes, orchid flower, lion statue (Merlion)" },
      { code: "VN", name: "Vietnam", currency: "VND", currencyName: "Đồng", figures: "Plastic/polymer, same bearded man with goatee on all notes, temples, pink/blue/green" },
      { code: "NG", name: "Nigeria", currency: "NGN", currencyName: "Naira", figures: "Men in traditional caps, green/brown tones" },
      { code: "ZA", name: "South Africa", currency: "ZAR", currencyName: "Rand", figures: "Smiling bald man (Mandela) on all notes, elephant/rhino/lion/buffalo/leopard on back" },
      { code: "KE", name: "Kenya", currency: "KES", currencyName: "Shilling", figures: "Lion, rhino, elephant, colorful, Kenyatta Conference Centre" },
      { code: "TZ", name: "Tanzania", currency: "TZS", currencyName: "Shilling", figures: "Man with round cap, giraffe, elephant, Kilimanjaro" },
      { code: "UG", name: "Uganda", currency: "UGX", currencyName: "Shilling", figures: "Crested crane bird, mountain gorillas" },
      { code: "GH", name: "Ghana", currency: "GHS", currencyName: "Cedi", figures: "Group of 6 men (Big Six), cocoa pods, dam" },
      { code: "SN", name: "Senegal (CFA)", currency: "XOF", currencyName: "CFA Franc", figures: "African mask/head sculpture, fish, traditional patterns" },
      { code: "CM", name: "Cameroon (CFA)", currency: "XAF", currencyName: "CFA Franc", figures: "Traditional African patterns, animals, oil rigs" },
      { code: "ZM", name: "Zambia", currency: "ZMW", currencyName: "Kwacha", figures: "Eagle, Victoria Falls waterfall" },
      { code: "ZW", name: "Zimbabwe", currency: "ZWL", currencyName: "Dollar", figures: "Balancing rocks, elephant, dam" },
      { code: "MW", name: "Malawi", currency: "MWK", currencyName: "Kwacha", figures: "Man with sunglasses, fish eagle" },
      { code: "MZ", name: "Mozambique", currency: "MZN", currencyName: "Metical", figures: "Man in military cap, rhino, elephant" },
      { code: "AO", name: "Angola", currency: "AOA", currencyName: "Kwanza", figures: "Two men portraits, waterfalls, antelopes" },
      { code: "CD", name: "DR Congo", currency: "CDF", currencyName: "Franc", figures: "Okapi (giraffe-like animal), tribal masks, man portrait" },
      { code: "RW", name: "Rwanda", currency: "RWF", currencyName: "Franc", figures: "Mountain gorillas, tea fields, modern buildings" },
      { code: "MG", name: "Madagascar", currency: "MGA", currencyName: "Ariary", figures: "Lemurs (big-eyed primates), baobab trees" },
      { code: "MU", name: "Mauritius", currency: "MUR", currencyName: "Rupee", figures: "Man with glasses, dodo bird drawing" },
      { code: "FJ", name: "Fiji", currency: "FJD", currencyName: "Dollar", figures: "Tropical fish, iguana, parrot, palm trees" },
      { code: "PG", name: "Papua New Guinea", currency: "PGK", currencyName: "Kina", figures: "Bird of paradise, tribal painted face masks" },
      { code: "WS", name: "Samoa", currency: "WST", currencyName: "Tala", figures: "Man in traditional dress, palm trees, beach" },
    ],
  },
  {
    id: "latin-turkish",
    nameKey: "identify.scripts.turkish",
    icon: "flag-outline",
    countries: [
      { code: "TR", name: "Turkey", currency: "TRY", currencyName: "Lira", figures: "Same man on all notes (side profile, serious face), purple/red/green/brown, 'TÜRKİYE CUMHURİYET MERKEZ BANKASI'" },
      { code: "AZ", name: "Azerbaijan", currency: "AZN", currencyName: "Manat", figures: "Musical instruments (tar, kamancha), tower, ornamental patterns" },
      { code: "TM", name: "Turkmenistan", currency: "TMT", currencyName: "Manat", figures: "Man in traditional hat, palace, mosque, horse (Akhal-Teke)" },
    ],
  },
  {
    id: "greek",
    nameKey: "identify.scripts.greek",
    icon: "library-outline",
    countries: [
      { code: "GR", name: "Greece (Drachma)", currency: "GRD", currencyName: "Δραχμή", figures: "Greek god statues (young man, woman with helmet), ΔΡΑΧΜΕΣ/ΤΡΑΠΕΖΑ ΤΗΣ ΕΛΛΑΔΟΣ text, ancient coins" },
      { code: "CY", name: "Cyprus (pre-Euro)", currency: "CYP", currencyName: "Pound", figures: "Mosaic art, ancient pottery, Mediterranean motifs" },
    ],
  },
  {
    id: "arabic",
    nameKey: "identify.scripts.arabic",
    icon: "moon-outline",
    countries: [
      { code: "SA", name: "Saudi Arabia", currency: "SAR", currencyName: "Riyal", figures: "Man in white headscarf (King), Kaaba (black cube building), green tones" },
      { code: "EG", name: "Egypt", currency: "EGP", currencyName: "Pound", figures: "Pharaoh golden mask, sphinx, pyramids, mosque with minarets, brown/green" },
      { code: "IQ", name: "Iraq", currency: "IQD", currencyName: "Dinar", figures: "Winged bull statue (lamassu), arched university building, minaret" },
      { code: "IR", name: "Iran", currency: "IRR", currencyName: "Rial", figures: "Bearded man with turban & glasses (Khomeini) on all notes, mosque dome, mountain" },
      { code: "AE", name: "UAE", currency: "AED", currencyName: "Dirham", figures: "Falcon, mosque, traditional boat (dhow), fort, red/green/purple" },
      { code: "JO", name: "Jordan", currency: "JOD", currencyName: "Dinar", figures: "Man in keffiyeh (King), rock-carved city (Petra), camels" },
      { code: "KW", name: "Kuwait", currency: "KWD", currencyName: "Dinar", figures: "Kuwait Towers, dhow" },
      { code: "QA", name: "Qatar", currency: "QAR", currencyName: "Riyal", figures: "Dhow, falcon, corniche" },
      { code: "OM", name: "Oman", currency: "OMR", currencyName: "Rial", figures: "Sultan Qaboos, Nakhal Fort" },
      { code: "BH", name: "Bahrain", currency: "BHD", currencyName: "Dinar", figures: "Bahrain Fort, Al Fateh Grand Mosque" },
      { code: "LY", name: "Libya", currency: "LYD", currencyName: "Dinar", figures: "Omar Al-Mukhtar, Leptis Magna" },
      { code: "TN", name: "Tunisia", currency: "TND", currencyName: "Dinar", figures: "Habib Bourguiba, amphitheatre El Jem" },
      { code: "DZ", name: "Algeria", currency: "DZD", currencyName: "Dinar", figures: "Emir Abdelkader, Sahara, Tassili" },
      { code: "MA", name: "Morocco", currency: "MAD", currencyName: "Dirham", figures: "King Mohammed VI, Hassan II Mosque" },
      { code: "YE", name: "Yemen", currency: "YER", currencyName: "Rial", figures: "Marib Dam, Shibam city" },
      { code: "SY", name: "Syria", currency: "SYP", currencyName: "Pound", figures: "Citadel of Aleppo, Palmyra" },
      { code: "LB", name: "Lebanon", currency: "LBP", currencyName: "Pound", figures: "Cedar tree, Baalbek ruins" },
      { code: "SD", name: "Sudan", currency: "SDG", currencyName: "Pound", figures: "People's Palace, dam" },
      { code: "SO", name: "Somalia", currency: "SOS", currencyName: "Shilling", figures: "Livestock, boats" },
      { code: "MR", name: "Mauritania", currency: "MRU", currencyName: "Ouguiya", figures: "Camel, palm trees" },
      { code: "PK", name: "Pakistan", currency: "PKR", currencyName: "Rupee", figures: "Muhammad Ali Jinnah, Faisal Mosque" },
      { code: "AF", name: "Afghanistan", currency: "AFN", currencyName: "Afghani", figures: "Mosque, mountains" },
    ],
  },
  {
    id: "cyrillic",
    nameKey: "identify.scripts.cyrillic",
    icon: "snow-outline",
    countries: [
      { code: "RU", name: "Russia", currency: "RUB", currencyName: "Ruble", figures: "Cities & monuments (no portraits), statue on column, bridge, cathedral dome, blue/green/red" },
      { code: "UA", name: "Ukraine", currency: "UAH", currencyName: "Hryvnia", figures: "Man with mustache and hat (poet), warrior with sword, church domes" },
      { code: "BY", name: "Belarus", currency: "BYN", currencyName: "Ruble", figures: "Buildings (library, opera, palace), no portraits, modern design" },
      { code: "RS", name: "Serbia", currency: "RSD", currencyName: "Dinar", figures: "Man with big mustache (Tesla), old bearded man, monastery" },
      { code: "BG", name: "Bulgaria", currency: "BGN", currencyName: "Lev", figures: "Monk with beard (Paisius), lion figure, brown/green" },
      { code: "MK", name: "North Macedonia", currency: "MKD", currencyName: "Denar", figures: "Samuil, icons, churches" },
      { code: "BA", name: "Bosnia & Herzegovina", currency: "BAM", currencyName: "Mark", figures: "Meša Selimović, Ivo Andrić" },
      { code: "KZ", name: "Kazakhstan", currency: "KZT", currencyName: "Tenge", figures: "Astana (Nur-Sultan), Bayterek tower" },
      { code: "KG", name: "Kyrgyzstan", currency: "KGS", currencyName: "Som", figures: "Toktogul Satylganov, Sulayman Mountain" },
      { code: "TJ", name: "Tajikistan", currency: "TJS", currencyName: "Somoni", figures: "Ismoil Somoni, Dushanbe" },
      { code: "UZ", name: "Uzbekistan", currency: "UZS", currencyName: "Sum", figures: "Amir Timur, Registan, Samarkand" },
      { code: "MN", name: "Mongolia", currency: "MNT", currencyName: "Tugrik", figures: "Genghis Khan (Chinggis Khaan)" },
      { code: "GE", name: "Georgia", currency: "GEL", currencyName: "Lari", figures: "Niko Pirosmani, Queen Tamar" },
      { code: "AM", name: "Armenia", currency: "AMD", currencyName: "Dram", figures: "Mount Ararat, Hovhannes Tumanyan" },
    ],
  },
  {
    id: "cjk",
    nameKey: "identify.scripts.cjk",
    icon: "globe-outline",
    countries: [
      { code: "JP", name: "Japan", currency: "JPY", currencyName: "Yen ¥", figures: "Man in suit (older notes), woman in kimono, Mount Fuji, cherry blossoms, blue/brown" },
      { code: "CN", name: "China", currency: "CNY", currencyName: "Yuan ¥", figures: "Same man on ALL notes (Mao, round face, mole on chin), red 100¥, green 50¥, Great Wall" },
      { code: "TW", name: "Taiwan", currency: "TWD", currencyName: "Dollar", figures: "Bald man in suit (Sun Yat-sen), baseball players, blue/red/purple" },
      { code: "KR", name: "South Korea", currency: "KRW", currencyName: "Won ₩", figures: "Man with traditional hat (Sejong), woman painting grapes, turtle ship, green/yellow" },
      { code: "KP", name: "North Korea", currency: "KPW", currencyName: "Won", figures: "Man with receding hair (Kim Il-sung), tower, workers monument" },
    ],
  },
  {
    id: "south-asian",
    nameKey: "identify.scripts.southAsian",
    icon: "flower-outline",
    countries: [
      { code: "IN", name: "India", currency: "INR", currencyName: "Rupee ₹", figures: "Bald man with round glasses (Gandhi) on ALL notes, ₹ symbol, red fort, satellite, colorful" },
      { code: "BD", name: "Bangladesh", currency: "BDT", currencyName: "Taka", figures: "Man with thick glasses on all notes, parliament building (lotus shape), green/purple" },
      { code: "NP", name: "Nepal", currency: "NPR", currencyName: "Rupee", figures: "Mount Everest, yak (hairy ox), snow leopard, man with traditional cap" },
      { code: "LK", name: "Sri Lanka", currency: "LKR", currencyName: "Rupee", figures: "Traditional dancers, colorful birds, elephants, ancient temple" },
      { code: "BT", name: "Bhutan", currency: "BTN", currencyName: "Ngultrum", figures: "Young king in traditional robe, fortress (dzong), dragon" },
      { code: "MV", name: "Maldives", currency: "MVR", currencyName: "Rufiyaa", figures: "Traditional sailing boat (dhow), coconut palm, tuna fish" },
      { code: "MM", name: "Myanmar", currency: "MMK", currencyName: "Kyat", figures: "Lion guardian statue (chinthe), temple, man in military cap" },
    ],
  },
  {
    id: "southeast-asian",
    nameKey: "identify.scripts.southeastAsian",
    icon: "leaf-outline",
    countries: [
      { code: "TH", name: "Thailand", currency: "THB", currencyName: "Baht ฿", figures: "King in military uniform or suit, golden temples, brown/purple/green/blue" },
      { code: "KH", name: "Cambodia", currency: "KHR", currencyName: "Riel", figures: "Ancient temple towers (Angkor Wat), king in suit, green/red" },
      { code: "LA", name: "Laos", currency: "LAK", currencyName: "Kip", figures: "Man in suit, golden pagoda/stupa (That Luang), river scenes" },
    ],
  },
  {
    id: "ethiopic",
    nameKey: "identify.scripts.ethiopic",
    icon: "sunny-outline",
    countries: [
      { code: "ET", name: "Ethiopia", currency: "ETB", currencyName: "Birr", figures: "Castle/fortress, coffee plants, farmers harvesting, unique script" },
      { code: "ER", name: "Eritrea", currency: "ERN", currencyName: "Nakfa", figures: "Three young girls, camel, sailing ship, unique script" },
    ],
  },
  {
    id: "hebrew",
    nameKey: "identify.scripts.hebrew",
    icon: "star-outline",
    countries: [
      { code: "IL", name: "Israel", currency: "ILS", currencyName: "Shekel ₪", figures: "Portraits of men/women poets, right-to-left text, ₪ symbol, blue/green/red" },
    ],
  },

  // ─── By Visual Feature ──────────────────────────────────────────────────
  {
    id: "polymer",
    nameKey: "identify.scripts.polymer",
    icon: "card-outline",
    countries: [
      { code: "AU", name: "Australia", currency: "AUD", currencyName: "Dollar", figures: "Transparent window, hologram" },
      { code: "CA", name: "Canada", currency: "CAD", currencyName: "Dollar", figures: "Transparent maple leaf window" },
      { code: "GB", name: "United Kingdom", currency: "GBP", currencyName: "Pound", figures: "Transparent crown window" },
      { code: "NZ", name: "New Zealand", currency: "NZD", currencyName: "Dollar", figures: "Transparent fern window" },
      { code: "RO", name: "Romania", currency: "RON", currencyName: "Leu", figures: "First polymer notes in Europe" },
      { code: "SG", name: "Singapore", currency: "SGD", currencyName: "Dollar", figures: "Polymer notes since 1990s" },
      { code: "VN", name: "Vietnam", currency: "VND", currencyName: "Đồng", figures: "All polymer series" },
      { code: "BR", name: "Brazil", currency: "BRL", currencyName: "Real", figures: "200 Real polymer note" },
      { code: "NG", name: "Nigeria", currency: "NGN", currencyName: "Naira", figures: "Polymer series" },
    ],
  },

  // ─── Historical / Defunct ───────────────────────────────────────────────
  {
    id: "historical",
    nameKey: "identify.scripts.historical",
    icon: "time-outline",
    countries: [
      { code: "SU", name: "Soviet Union", currency: "SUR", currencyName: "Ruble", figures: "Bald man with goatee (Lenin), 'CCCP' text, hammer & sickle, Kremlin, red star" },
      { code: "YU", name: "Yugoslavia", currency: "YUD", currencyName: "Dinar", figures: "Man in military uniform (Tito), 'SFRJ' text, industrial scenes" },
      { code: "DE", name: "Germany (Mark)", currency: "DEM", currencyName: "Deutsche Mark", figures: "Women portraits, piano, architectural drawings, 'DEUTSCHE BUNDESBANK'" },
      { code: "FR", name: "France (Franc)", currency: "FRF", currencyName: "Franc", figures: "Man with airplane (Saint-Exupéry, Little Prince), Eiffel Tower, blue/brown" },
      { code: "IT", name: "Italy (Lira)", currency: "ITL", currencyName: "Lira", figures: "'MILLE LIRE' text, woman/man portraits, artists, 'BANCA D'ITALIA'" },
      { code: "ES", name: "Spain (Peseta)", currency: "ESP", currencyName: "Peseta", figures: "Man with crown (King), conquistador, 'BANCO DE ESPAÑA'" },
      { code: "GR", name: "Greece (Drachma)", currency: "GRD", currencyName: "Drachma", figures: "Greek god statues, ΔΡΑΧΜΕΣ text, ancient coins, ΤΡΑΠΕΖΑ ΤΗΣ ΕΛΛΑΔΟΣ" },
      { code: "AT", name: "Austria (Schilling)", currency: "ATS", currencyName: "Schilling", figures: "Man with white wig (Mozart), woman portrait, 'OESTERREICHISCHE NATIONALBANK'" },
      { code: "NL", name: "Netherlands (Gulden)", currency: "NLG", currencyName: "Gulden", figures: "Sunflower, abstract geometric art, very modern design" },
      { code: "PT", name: "Portugal (Escudo)", currency: "PTE", currencyName: "Escudo", figures: "Man with beard (navigator), sailing ship, 'BANCO DE PORTUGAL'" },
      { code: "FI", name: "Finland (Markka)", currency: "FIM", currencyName: "Markka", figures: "Man with beard and wild hair (Sibelius), nature, 'SUOMEN PANKKI'" },
      { code: "IE", name: "Ireland (Punt)", currency: "IEP", currencyName: "Punt", figures: "Beautiful woman portrait on all notes, Celtic designs, green tones" },
      { code: "BE", name: "Belgium (Franc)", currency: "BEF", currencyName: "Franc", figures: "Man with bowler hat (Magritte-style), King portrait" },
      { code: "CZ", name: "Czechoslovakia", currency: "CSK", currencyName: "Koruna", figures: "Man with glasses and mustache, castle, 'ČESKOSLOVENSKO'" },
      { code: "TR", name: "Ottoman Empire", currency: "OTT", currencyName: "Kuruş", figures: "Elaborate calligraphy seal (tughra), ornate borders, Arabic script" },
      { code: "DE", name: "East Germany (DDR)", currency: "DDM", currencyName: "Mark", figures: "Workers, factories, man with big beard (Marx), 'DDR' text" },
    ],
  },
];
